#ifndef SYSTIC_PRIVATE_H_
#define SYSTIC_PRIVATE_H_

#define SYST_CLKSRC_SHIFT		2U
#define SYST_CLKSRC_MASK		1U

#define SYST_INT_MASK			1U
#define SYST_INT_SHIFT			1U

#define SYST_ENABLE_MASK		0b11

#define SYST_COUNT_FLAG_SHIFT	16U
#define SYST_COUNT_FLAG_ANDIG	1U
#define SYST_COUNT_FLAG_MASK	1U


#define SYSTICK_TIMEOUT			200000UL

#define SYSTICK_SPEED			16000000U
#define SYSTICK_MILLI			1000U
#define SYSTICK_MICRO			1000000U
#endif
